#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
UnicodeData.txt parser script for the ucsspell project.
Extracts N* (Number) category code points as a C++ char32_t array.
"""

import os

LOCAL_FILE = "UnicodeData.txt"


def parse_numbers(target_categories=None):
    """
    Extracts number categories from UnicodeData.txt.
    By default, extracts N* (Nd, Nl, No) categories.
    """
    if target_categories is None:
        target_categories = ["Nd", "Nl", "No"]

    number_list = []
    
    with open(LOCAL_FILE, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            
            fields = line.split(";")
            if len(fields) < 3:
                continue
            
            code_hex = fields[0]
            char_name = fields[1]
            category = fields[2]
            
            if category in target_categories:
                code_point = int(code_hex, 16)
                number_list.append((code_point, code_hex, char_name, category))
                
    return number_list

def generate_cpp_header(number_list, output_file="../src/hunspell/ucs_digits_data.hxx"):
    """Generates a C++ compatible array header file with comments."""
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("// Automatically generated by parse_digits.py\n")
        f.write("// DO NOT EDIT MANUALLY\n\n")
        f.write("#ifndef UCS_DIGITS_DATA_HXX\n")
        f.write("#define UCS_DIGITS_DATA_HXX\n\n")
        f.write("#include <cstddef>\n\n")
        f.write("namespace ucs {\n\n")
        f.write(f"// Total number code points: {len(number_list)}\n")
        f.write("constexpr char32_t UNICODE_DIGITS[] = {\n")
        
        for code_point, code_hex, char_name, category in number_list:
            f.write(f"    0x{code_hex:>04s}, // [{category}] {char_name}\n")
            
        f.write("};\n\n")
        f.write("constexpr size_t NUM_UNICODE_DIGITS = ")
        f.write("sizeof(UNICODE_DIGITS) / sizeof(UNICODE_DIGITS[0]);\n\n")
        f.write("} // namespace ucs\n\n")
        f.write("#endif // UCS_DIGITS_DATA_HXX\n")

    print(f"Done! C++ header written to '{output_file}'.")

if __name__ == "__main__":
    numbers = parse_numbers(["Nd", "Nl", "No"])
    print(f"Found number code points: {len(numbers)}")
    generate_cpp_header(numbers)
