#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
UnicodeData.txt parser script.
Extracts P* (Punctuation) category code points as a C++ char32_t array.
"""

import os


LOCAL_FILE = "UnicodeData.txt"

def parse_punctuation():
    """Extracts all punctuation code points from UnicodeData.txt."""
    punct_list = []
    
    with open(LOCAL_FILE, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            
            fields = line.split(";")
            if len(fields) < 3:
                continue
            
            code_hex = fields[0]
            char_name = fields[1]
            category = fields[2]
            
            # Filter all P* (Punctuation) categories:
            # Pd (Dash), Ps (Open), Pe (Close), Pi (Initial quote), Pf (Final quote), Po (Other)
            if category.startswith("P"):
                code_point = int(code_hex, 16)
                punct_list.append((code_point, code_hex, char_name, category))
                
    return punct_list

def generate_cpp_header(punct_list, output_file="../src/hunspell/ucs_punct_data.hxx"):
    """Generates a C++ compatible array header file with comments."""
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("// Automatically generated by parse_ucd.py\n")
        f.write("// DO NOT EDIT MANUALLY\n\n")
        f.write("#ifndef UCS_PUNCT_DATA_HXX\n")
        f.write("#define UCS_PUNCT_DATA_HXX\n\n")
        f.write("#include <cstddef>\n\n")
        f.write("namespace ucs {\n\n")
        f.write(f"// Total punctuation code points: {len(punct_list)}\n")
        f.write("constexpr char32_t UNICODE_PUNCTUATIONS[] = {\n")
        
        for code_point, code_hex, char_name, category in punct_list:
            f.write(f"    0x{code_hex:>04s}, // [{category}] {char_name}\n")
            
        f.write("};\n\n")
        f.write("constexpr size_t NUM_UNICODE_PUNCT = ")
        f.write("sizeof(UNICODE_PUNCTUATIONS) / sizeof(UNICODE_PUNCTUATIONS[0]);\n\n")
        f.write("} // namespace ucs\n\n")
        f.write("#endif // UCS_PUNCT_DATA_HXX\n")

    print(f"Done! C++ header written to '{output_file}'.")

if __name__ == "__main__":
    punctuations = parse_punctuation()
    print(f"Found punctuation code points: {len(punctuations)}")
    generate_cpp_header(punctuations)
